baseURL = "http://example.com/"
title = "EchoSlate"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

[outputs]
  home = ["HTML", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    name = "SearchIndex"
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "EchoSlate"
    contentDir = "content/en"
    [languages.en.params]
      description = "A digital portfolio website to showcase resumes and projects."
    [languages.en.outputs]
      home = ["HTML", "SearchIndex"]

    [[languages.en.menu.main]]
      identifier = "home"
      name = "home"
      url = "/"
      weight = 1

    [[languages.en.menu.main]]
      identifier = "users"
      name = "users"
      url = "/users/"
      weight = 2

    [[languages.en.menu.main]]
      identifier = "edit"
      name = "edit"
      url = "/edit/"
      weight = 3

    [[languages.en.menu.main]]
      identifier = "upload"
      name = "upload"
      url = "/upload/"
      weight = 4

    [[languages.en.menu.main]]
      identifier = "search"
      name = "search"
      url = "/search/"
      weight = 5

    [[languages.en.menu.main]]
      identifier = "about"
      name = "about"
      url = "/about/"
      weight = 6

    [[languages.en.menu.main]]
      identifier = "contact"
      name = "contact"
      url = "/contact/"
      weight = 7

  [languages.es]
    languageName = "Español"
    weight = 2
    title = "EchoSlate"
    contentDir = "content/es"
    [languages.es.params]
      description = "Un sitio web de portafolio digital para mostrar currículums y proyectos."
    [languages.es.outputs]
      home = ["HTML", "SearchIndex"]

    [[languages.es.menu.main]]
      identifier = "home"
      name = "home"
      url = "/es/"
      weight = 1

    [[languages.es.menu.main]]
      identifier = "users"
      name = "users"
      url = "/es/users/"
      weight = 2

    [[languages.es.menu.main]]
      identifier = "edit"
      name = "edit"
      url = "/es/edit/"
      weight = 3

    [[languages.es.menu.main]]
      identifier = "upload"
      name = "upload"
      url = "/es/upload/"
      weight = 4

    [[languages.es.menu.main]]
      identifier = "search"
      name = "search"
      url = "/es/search/"
      weight = 5

    [[languages.es.menu.main]]
      identifier = "about"
      name = "about"
      url = "/es/about/"
      weight = 6
      
    [[languages.es.menu.main]]
      identifier = "contact"
      name = "contact"
      url = "/es/contact/"
      weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    noClasses = false  # Set to true to disable CSS classes for code highlighting
